[package]
name = "oshome-web_server"
version = "0.3.7"
authors = ["Daniel Habenicht <daniel-habenicht@outlook.de>"]
edition = "2021"

[dependencies]
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
axum = "0.7.9"
tower-http = { version = "0.6.1", features = ["timeout", "trace"] }

oshome-core = { path = "../core" }
tokio = { version = "1", features = ["full"] }
