[package]
name = "oshome"
version = "0.1.0"
authors = ["Daniel Habenicht <daniel-habenicht@outlook.de>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4.5.21", features = [ "derive" ] }
rust-embed = "6.8"
env_logger = "0.11.7"
log = "0.4"
rumqttc = "0.24.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
oshome-mqtt = { path = "components/mqtt" }
oshome-shell = { path = "components/shell" }
oshome-core = { path = "components/core" }
oshome-web_server = { path = "components/web_server" }

[workspace]
resolver = "2"
members = ["components/mqtt", "components/shell", "components/core", "components/web_server"]
