[package]
name = "os-home"
version = "0.1.0"
authors = ["Daniel Habenicht <daniel-habenicht@outlook.de>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6.1", features = ["timeout", "trace"] }
clap = { version = "4.5.21", features = [ "derive" ] }
axum = "0.7.9"
rust-embed = "6.8"
env_logger = "0.11.7"
log = "0.4"
rumqttc = "0.24.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
os-home-mqtt = { path = "components/mqtt" }

[workspace]
resolver = "2"
members = ["components/mqtt"]
