oshome:
  name: new_awesome

mqtt: 
  broker: 192.168.178.167
  username: test
  password: a887aeda-7248-4b0f-a2e7-6f4ee0026f5e

shell: 
  type: powershell

button: 
 - platform: shell
   id: my_button
   name: "Write Hello World"
   command: "echo 'Hello World Daniel' >> test.log"

sensor:
  - platform: shell
    name: "RAM Usage"
    id: ram_usage
    icon: "mdi:bluetooth-settings"
    # device_class: "data_size"
    state_class: "measurement"
    unit_of_measurement: "%"
    update_interval: 30s # 0 only executes it once and assumes a long running processes.
    command: |-
      free | grep Mem | awk '{print $3/$2 * 100.0}'
    # entity_category: "diagnostic"
    # lambda: |-
    #   int limit = bluetooth_proxy::global_bluetooth_proxy->get_bluetooth_connections_limit();
    #   ESP_LOGD("bluetooth_proxy_sensor", "Current connections limit => %d", limit);
    #   return limit;


# TODO: Things still to implement...
# TODO: Dynamic compilation based on configured options - currently everything is compiled.
os:
  type: windows

text_sensor:
  - platform: version
    name: "Firmware"

binary_sensor:
  - platform: shell
    device_class: motion

# Native Homeassistant API
api:
  encryption:
    key: "F7KLwAYmqlV674MaKfqa5tBehkccYSqsTGtzKQwhAm4="

# Enable Automatic updates
ota:
  - platform: oshome
    password: "ea04d2dc1adb3b82edea4b97ced1cc7c"