oshome:
  name: new_awesome

# mqtt: 
#   broker: 127.0.0.1
#   port: 1883
#   username: user
#   password: password

mqtt: 
  broker: 192.168.178.167
  username: test
  password: a887aeda-7248-4b0f-a2e7-6f4ee0026f5e

gpio:
  device: raspberryPi

shell: 
  type: bash

button: 
 - platform: shell
   id: my_button
   name: "Write Hello World"
   command: "echo 'Hello World!' >> test.log"

sensor:
  # - platform: dht22

  - platform: shell
    name: "RAM Usage"
    id: ram_usage
    icon: mdi:memory
    # device_class: "data_size"
    state_class: "measurement"
    unit_of_measurement: "%"
    update_interval: 30s # 0 only executes it once and assumes a long running processes.
    command: |-
      free | grep Mem | awk '{print $3/$2 * 100.0}'

binary_sensor:
  - platform: shell
    name: "Bluetooth Device connected"
    id: bluetooth_connected
    icon: "mdi:bluetooth-settings"
    device_class: presence
    update_interval: 10s
    command: |-
      if hcitool con | grep -q "00:12:6F:F1:FF:61"; then
          echo true
      else
          echo false
      fi
  - platform: gpio
    name: "Motion"
    id: motion
    device_class: presence
    pin: 23


# TODO: Things still to implement...
# TODO: Dynamic compilation based on configured options - currently everything is compiled.
os:
  type: windows

text_sensor:
  - platform: version
    name: "Firmware"



# Native Homeassistant API
api:
  encryption:
    key: "token"

# Enable Automatic updates
ota:
  - platform: oshome
    password: "ea04d2dc1adb3b82edea4b97ced1cc7c"