# TODO: Dynamic compilation based on configured options - currently everything is compiled.
oshome:
  name: new_awesome
os:
  type: windows

mqtt: 
  broker: 192.168.178.167
  username: test
  password: a887aeda-7248-4b0f-a2e7-6f4ee0026f5e

shell: 
  type: powershell

button: 
 - platform: shell
   id: my_button
   name: "Say Hello World"
   command: "echo 'Hello World Daniel'"