# https://github.com/cross-rs/cross/blob/main/docs/config_file.md
[target.armv7-unknown-linux-musleabi]
pre-build = [
    "apt-get update",
    "apt-get install -y libdbus-1-dev pkg-config",
]

[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update",
    "apt-get install -y libdbus-1-dev pkg-config",
]