nav:
  - Home: index.md
  - Getting started: getting_started/index.md
  - Features: 
    - features/index.md
    - Connectivity:
      - features/connectivity/index.md
      - MQTT: features/connectivity/mqtt.md
      - HTTP: features/connectivity/http.md
      - Web Server: features/connectivity/web_server.md
    - Components:
      - features/components/index.md
      - Button: features/components/button.md
      - Sensor: features/components/sensor.md
      - Binary Sensor: features/components/binary_sensor.md
    - Platforms:
      - features/platforms/index.md
      - Shell: features/platforms/shell.md
  - Examples:
    - "examples/*"