[package]
name = "oshome-api"
version = "0.3.1"
authors = ["Daniel Habenicht <daniel-habenicht@outlook.de>"]
edition = "2021"

[dependencies]
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
oshome-core = { path = "../core" }
prost = "0.13.5"
tonic = "0.13"
tower = "0.5.2"

[build-dependencies]
prost-build = "0.13"
