site_name: OSHome
repo_url: https://github.com/DanielHabenicht/OSHome
extra:
  homepage: https://example.com
plugins:
  - search
  - social
  - offline
nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Features: 
    - features/index.md
    - Connectivity:
      - features/connectivity/index.md
      - MQTT: features/connectivity/mqtt.md
      - HTTP: features/connectivity/http.md
      - Web Server: features/connectivity/web_server.md
    - Components:
      - features/components/index.md
      - Button: features/components/button.md
      - Sensor: features/components/sensor.md
      - Binary Sensor: features/components/binary_sensor.md
    - Platforms:
      - features/platforms/index.md
      - Shell: features/platforms/shell.md
theme:
  name: material
  language: en
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  # logo: assets/logo.png
  # favicon: images/favicon.png

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes 
    - toc.follow
    - navigation.top
    - search
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate 
    - content.tabs.link
    - content.tooltips
    - content.footnote.tooltips
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - abbr
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.betterem
