name: CI

on:
  # push:
  #   branches: [ main ]
      
  pull_request:

    
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            runs-on: ubuntu-24.04
            fileending: ""
          # - target: aarch64-unknown-linux-gnu # tested on aws t4g.nano
          #   os: ubuntu-latest
          # - target: armv7-unknown-linux-gnueabihf # raspberry pi 2-3-4, not tested
          #   os: ubuntu-latest
          # - target: arm-unknown-linux-gnueabihf # raspberry pi 0-1, not tested
          #   os: ubuntu-latest
          - target: x86_64-apple-darwin # tested on a mac, is not properly signed so there are security warnings
            runs-on: macOS-latest
            fileending: ""
          - target: x86_64-pc-windows-msvc # tested on a windows machine
            runs-on: windows-latest
            fileending: ".exe"
          - target: armv7-unknown-linux-musleabi
            runs-on: ubuntu-24.04
            fileending: ""
    uses: ./.github/workflows/build-and-test-template.yml
    with:
      os: ${{ matrix.os }}
    # If you might want to use a secret in the build or test job then you would need to pass secrets, inherit disables secret isolation
    secrets: inherit

