name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: cargo build --release # --verbose
    - name: Run tests
      run: cargo test # --verbose

      # Save executable
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-without-markdown
        path: |
          target/release
