name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.8
      with:
        key: release

    - name: Build
      run: cargo build --release
      
    - name: Prepare artifacts tests
      run: |
        rm -r target/release/deps
        rm -r target/release/build

    # Save executable
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.os }}
        path: |
          target/release



  # test:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest, macos-latest]

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Rust
  #     uses: actions-rs/toolchain@v1
  #     with:
  #       toolchain: stable

  #   - name: Rust Cache
  #     uses: Swatinem/rust-cache@v2.7.8
  #     with:
  #       key: test

  #   - name: Run tests
  #     run: cargo test