name: Release

on:
  push:
    # # Just for debugging
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    permissions:
      contents: write
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl
            
          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            
          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin

          - os-name: Linux-debian
            target: armv7-unknown-linux-musleabi
            runs-on: ubuntu-24.04

          # - os-name: Linux-riscv64
          #   runs-on: ubuntu-24.04
          #   target: riscv64gc-unknown-linux-gnu

          # - os-name: FreeBSD-x86_64
          #   runs-on: ubuntu-24.04
          #   target: x86_64-unknown-freebsd

          # - os-name: Linux-aarch64
          #   runs-on: ubuntu-24.04
          #   target: aarch64-unknown-linux-musl

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Add extra packages (MacOS)
      #   if: matrix.platform.runs-on == 'macOS-latest'
      #   run: brew install libmodbus

      - name: Add extra packages (Linux)
        if: matrix.platform.runs-on == 'ubuntu-24.04'
        run: | 
          sudo apt-get update
          sudo apt-get install -y musl-tools
          export PKG_CONFIG_SYSROOT_DIR=/

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          # Add "--locked" again when release please is not updating all Cargo.toml files
          args: "--release"
          strip: true
          force-use-cross: ${{ matrix.platform.target == 'x86_64-unknown-linux-musl' }}

      # - name: Publish artifacts and release
      #   uses: houseabsolute/actions-rust-release@v0
      #   with:
      #     executable-name: oshome
      #     target: ${{ matrix.platform.target }}
      #     changes-file: null
      #     extra-files: |
      #       README.md
      #       config.yaml

      # https://octokit.github.io/rest.js/v21/
      # - name: Update docs version numbers
      #   uses: actions/github-script@v5
      #   with:
      #     script: |
      #       await github.rest.actions.createWorkflowDispatch({
      #         'Mause',
      #         'fdroidrepo',
      #         'workflows/update.yaml',
      #         'main',
      #       });