name: Release

on:
  push:
    # Just for debugging
    # branches: [ main ]
    tags:
      - 'v*'

jobs:
  release:
    name: Release - ${{ matrix.target }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl
            
          - runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            
          - runs-on: macOS-latest
            target: x86_64-apple-darwin

          - target: armv7-unknown-linux-musleabi
            runs-on: ubuntu-24.04

          # - runs-on: ubuntu-24.04
          #   target: riscv64gc-unknown-linux-gnu

          # - runs-on: ubuntu-24.04
          #   target: x86_64-unknown-freebsd

          # - runs-on: ubuntu-24.04
          #   target: aarch64-unknown-linux-musl

    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add extra packages (MacOS)
        if: matrix.runs-on == 'macOS-latest'
        run: brew install libmodbus

      - name: Add extra packages (Linux)
        if: matrix.runs-on == 'ubuntu-24.04'
        run: sudo apt install -y libdbus-1-dev pkg-config

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.target }}
          # Add "--locked" again when release please is not updating all Cargo.toml files
          args: "--release"
          strip: true

      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: ubihome
          target: ${{ matrix.target }}
          changes-file: null
          extra-files: |
            README.md
            config.yaml

      # https://octokit.github.io/rest.js/v21/
      - name: Update docs version numbers
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.CUSTOM_GITHUB_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'UbiHome',
              repo: 'ubihome.github.io',
              workflow_id: 'update_version.yml',
              ref: 'main',
              inputs: {
                version: context.payload.ref.replace('refs/tags/v', ''),
              }
            });
