name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
            target: [x86_64-unknown-linux-musl, x86_64-pc-windows-gnu, x86_64-apple-darwin]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
  
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.8
        with:
          key: release
  
      - name: Build
        run: cargo build --release
        
      - name: Prepare artifacts tests
        run: |
          rm -r target/release/deps
          rm -r target/release/build
          rm -r target/release/examples
          rm -r target/release/incremental


      - name: Prepare artifact
        run: |
          mkdir -p artifact
          cp target/release/* artifact/
          zip -j artifact/${{ matrix.target }}-${{ github.ref_name }}.zip artifact/*

      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.ref_name }} artifact/${{ matrix.target }}-${{ github.ref_name }}.zip
